image:
  file: .gitpod.Dockerfile

ports:
  - port: 4000
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: open-browser

tasks:
  - name: Server
    init: |
      npm install
      npm run generate
    command: |
      export CLIENT_URL=$(gp url 3000)
      npm run dev

  - name: Client
    before: cd client
    init: |
      npm install
    command: |
      export SERVER_URL=$(gp url 4000)
      npm start

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - GraphQL.vscode-graphql
    - esbenp.prettier-vscode
    - Prisma.prisma
    - bradlc.vscode-tailwindcss
