version: '3.8'

services:
  server:
    build:
      context: ./server
    image: artsy-graphql
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file: ./server/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/image_sharing
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build:
      context: ./client
    image: artsy-react
    ports:
      - 3000:3000
    env_file: ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=image_sharing
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  server:
  client:
  db:
